- name: Setup Template
  ansible.builtin.template:
    src: sp_branch.xml
    dest: /tmp/sp_branch.xml


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sp_branch.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://172.31.85.130:8080
    user: admin